[project]
name = "unrar2-cffi"
dynamic = ["version"]

[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm", "cffi"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
