name: Build

on:
  push:
    branches:
      - master
      - develop
    tags:
      - v*
  pull_request:
    branches:
      - master
      - develop

env:
  UNRAR_VERSION: 6.2.8
  UNRAR_REV: df15c8c3c9f4105d3501bc477e80ac6b8e227677
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871

      - name: Install Python
        uses: actions/setup-python@19dfb7b659fa9e60c2f89c33335ab5f6f1792b6e
        with:
          python-version: "3.10"

      - name: Set up unrar
        run: |
          git clone https://github.com/pmachapman/unrar.git unrarsrc
          cd unrarsrc
          git checkout ${UNRAR_REV}
          rm -rf .git
          cd ..

      - name: Build sdist
        run: |
          pip install build
          python -m build --sdist .
          ls -l dist

      - uses: actions/upload-artifact@184d73b71b93c222403b2e7f1ffebe4508014249
        with:
          name: unrar2-cffi-sdist
          path: ./dist/unrar2-cffi-*.tar.gz

  build_wheels:
    strategy:
      fail-fast: false
      matrix:
        # Copied from numpy
        buildplat:
          - [ubuntu-24.04, manylinux_x86_64]
          - [ubuntu-24.04, musllinux_x86_64]
          - [macos-13, macosx_x86_64]
          - [macos-14, macosx_arm64]
          - [windows-2022, win_amd64]
          - [windows-2022, win_arm64]
          - [windows-2022, win32]

    runs-on: ${{ matrix.buildplat[0] }}
    env:
      IS_32_BIT: ${{ matrix.buildplat[1] == 'win32' }}

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871

      - name: Setup Python
        uses: actions/setup-python@19dfb7b659fa9e60c2f89c33335ab5f6f1792b6e
        with:
          python-version: "3.10"

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@719c55c4a5a93233ce33aa9366dc90396d60e0ee
        with:
          platforms: all

      - name: Setup MSVC (x64)
        if: runner.os == 'Windows' && matrix.buildplat[1] == 'win_amd64'
        uses: TheMrMilchmann/setup-msvc-dev@fb19abb8a41b3cf0340f5d1be17d420309232be6
        with:
          arch: x64
          sdk: "10.0.22621.0"
          toolset: 14.0

      - name: Setup MSVC (x86)
        if: runner.os == 'Windows' && matrix.buildplat[1] == 'win32'
        uses: TheMrMilchmann/setup-msvc-dev@fb19abb8a41b3cf0340f5d1be17d420309232be6
        with:
          arch: x86
          sdk: "10.0.22621.0"
          toolset: 14.3

      - name: Set up unrar
        run: |
          git clone https://github.com/pmachapman/unrar.git unrarsrc
          cd unrarsrc
          git checkout ${UNRAR_REV}
          cd ..

      - name: Build wheels
        uses: pypa/cibuildwheel@7940a4c0e76eb2030e473a5f864f291f63ee879b
        env:
          CIBW_PRERELEASE_PYTHONS: True
          CIBW_BUILD: "*-${{ matrix.buildplat[1] }}"
          # Do not build PyPy
          CIBW_SKIP: "pp*"
          # Test
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest {project}/tests -vvv"
          CIBW_BUILD_VERBOSITY: 1
          # CIBW_FREE_THREADED_SUPPORT: 1

      - name: Move wheels
        run: |
          mkdir -p dist
          mv wheelhouse/*.whl dist/

      - name: Upload wheels
        uses: actions/upload-artifact@184d73b71b93c222403b2e7f1ffebe4508014249
        with:
          name: unrar2-cffi-${{ matrix.buildplat[1] }}
          path: |
            dist/*.whl

  publish:
    name: Publish
    needs: [build_sdist, build_wheels]
    runs-on: ubuntu-22.04
    # Run only if tag is present
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871

      - name: Setup Python
        uses: actions/setup-python@19dfb7b659fa9e60c2f89c33335ab5f6f1792b6e
        with:
          python-version: "3.10"

      - name: Download artifacts
        uses: actions/download-artifact@d0ce8fd1167ed839810201de977912a090ab10a7
        with:
          path: dist
          pattern: unrar2-cffi-*
          merge-multiple: true

      - name: Publish PyPi Test
        uses: pypa/gh-action-pypi-publish@f7600683efdcb7656dec5b29656edb7bc586e597
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

      - name: Publish PyPi
        uses: pypa/gh-action-pypi-publish@f7600683efdcb7656dec5b29656edb7bc586e597
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
