name: Build

on:
  push:
    branches:
      - master
      - develop
    tags:
      - v*
  pull_request:
    branches:
      - master
      - develop

env:
  UNRAR_VERSION: 7.2.6
  UNRAR_REV: 7168ddbf03529a508aa495e0d4ae55af05ea3f53
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Install Python
        uses: actions/setup-python@c8813ba1bc76ebf779b911ad8ffccbf2e449cb48
        with:
          python-version: "3.10"

      - name: Set up unrar
        run: |
          git clone https://github.com/pmachapman/unrar.git unrarsrc
          cd unrarsrc
          git checkout ${UNRAR_REV}
          rm -rf .git
          cd ..

      - name: Build sdist
        run: |
          pip install build
          python -m build --sdist .
          ls -l dist

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: unrar2-cffi-sdist
          path: ./dist/unrar2_cffi-*.tar.gz

  build_wheels:
    strategy:
      fail-fast: false
      matrix:
        # Copied from numpy
        buildplat:
          - [ubuntu-24.04, manylinux_x86_64]
          - [ubuntu-24.04, musllinux_x86_64]
          - [macos-15-intel, macosx_x86_64]
          - [macos-26, macosx_arm64]
          - [windows-2025, win_amd64]

    runs-on: ${{ matrix.buildplat[0] }}
    env:
      IS_32_BIT: ${{ matrix.buildplat[1] == 'win32' }}

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Setup Python
        uses: actions/setup-python@c8813ba1bc76ebf779b911ad8ffccbf2e449cb48
        with:
          python-version: "3.10"

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@259a565a6f30a57c28f9ea913f2d359b43ff5fc9
        with:
          platforms: all

      - name: Setup MSVC (x64)
        if: runner.os == 'Windows' && matrix.buildplat[1] == 'win_amd64'
        uses: TheMrMilchmann/setup-msvc-dev@79dac248aac9d0059f86eae9d8b5bfab4e95e97c
        with:
          arch: x64
          sdk: "10.0.26100.0"
          toolset: 14.3
        env:
          VSCMD_DEBUG: 3

      - name: Set up unrar
        run: |
          git clone https://github.com/pmachapman/unrar.git unrarsrc
          cd unrarsrc
          git checkout ${UNRAR_REV}
          cd ..
        shell: bash

      - name: Build wheels
        uses: pypa/cibuildwheel@866ae747818f794bbaf572f7a651c4296dbfb33e
        env:
          CIBW_PRERELEASE_PYTHONS: True
          CIBW_BUILD: "*-${{ matrix.buildplat[1] }}"
          # Do not build PyPy
          CIBW_SKIP: "pp*"
          # Test
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest {project}/tests -vvv"
          CIBW_BUILD_VERBOSITY: 1
          # CIBW_FREE_THREADED_SUPPORT: 1

      - name: Move wheels
        run: |
          mkdir -p dist
          mv wheelhouse/*.whl dist/
        shell: bash

      - name: Upload wheels
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: unrar2-cffi-${{ matrix.buildplat[1] }}
          path: |
            dist/*.whl

  publish:
    name: Publish
    needs: [build_sdist, build_wheels]
    runs-on: ubuntu-24.04
    # Run only if tag is present
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      # Used for publishing to GH releases
      contents: write
      discussions: write

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Setup Python
        uses: actions/setup-python@c8813ba1bc76ebf779b911ad8ffccbf2e449cb48
        with:
          python-version: "3.10"

      - name: Download artifacts
        uses: actions/download-artifact@484a0b528fb4d7bd804637ccb632e47a0e638317
        with:
          path: dist
          pattern: unrar2-cffi-*
          merge-multiple: true

      - name: Publish PyPi
        uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247

      - name: Create changelog
        id: prepare-change
        run: |
          python3 tools/create_changelog.py
          # Fetch git tag contents subject
          VERSION_SUBJ=$(git tag -l --format='%(contents:subject)' ${{ github.ref }})
          echo "version_subject=$VERSION_SUBJ" >> "$GITHUB_OUTPUT"
        env:
          VERSION: ${{ github.ref }}

      - name: Release
        uses: softprops/action-gh-release@3efcac8951299998593f871640ea8059d6818655
        with:
          files: |
            dist/*
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          body_path: CHANGELOG-GENERATED.md
          name: ${{ steps.prepare-change.outputs.version_subject }}
